name: Frontend CI/CD

on:
  push:
    branches:
        - master
    paths:
      - 'app/frontend/**'
  pull_request:
    branches:
      - master
    paths:
      - 'app/frontend/**'

env:
  AWS_REGION: ap-northeast-1
  S3_BUCKET: tuan-bucket

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to S3
      run: |
        aws s3 sync applications/frontend s3://$S3_BUCKET --delete